<?php

namespace App\Imports;

use App\Models\UmurModel;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class UmurImport implements ToModel, WithHeadingRow
{
    public function model(array $row)
    {
        
        return new UmurModel([
            'kode' => $row['kode'],
            'wilayah' => $row['wilayah'],

            'nol_tahun_lk' => $row['nol_tahun_lk'],
            'nol_tahun_pr' => $row['nol_tahun_pr'],
            'satu_tahun_lk' => $row['satu_tahun_lk'],
            'satu_tahun_pr' => $row['satu_tahun_pr'],
            'dua_tahun_lk' => $row['dua_tahun_lk'],
            'dua_tahun_pr' => $row['dua_tahun_pr'],
            'tiga_tahun_lk' => $row['tiga_tahun_lk'],
            'tiga_tahun_pr' => $row['tiga_tahun_pr'],
            'empat_tahun_lk' => $row['empat_tahun_lk'],
            'empat_tahun_pr' => $row['empat_tahun_pr'],
            'lima_tahun_lk' => $row['lima_tahun_lk'],
            'lima_tahun_pr' => $row['lima_tahun_pr'],
            'enam_tahun_lk' => $row['enam_tahun_lk'],
            'enam_tahun_pr' => $row['enam_tahun_pr'],
            'tujuh_tahun_lk' => $row['tujuh_tahun_lk'],
            'tujuh_tahun_pr' => $row['tujuh_tahun_pr'],
            'delapan_tahun_lk' => $row['delapan_tahun_lk'],
            'delapan_tahun_pr' => $row['delapan_tahun_pr'],
            'sembilan_tahun_lk' => $row['sembilan_tahun_lk'],
            'sembilan_tahun_pr' => $row['sembilan_tahun_pr'],
            'sepuluh_tahun_lk' => $row['sepuluh_tahun_lk'],
            'sepuluh_tahun_pr' => $row['sepuluh_tahun_pr'],

            'sebelas_tahun_lk' => $row['sebelas_tahun_lk'],
            'sebelas_tahun_pr' => $row['sebelas_tahun_pr'],
            'dua_belas_tahun_lk' => $row['dua_belas_tahun_lk'],
            'dua_belas_tahun_pr' => $row['dua_belas_tahun_pr'],
            'tiga_belas_tahun_lk' => $row['tiga_belas_tahun_lk'],
            'tiga_belas_tahun_pr' => $row['tiga_belas_tahun_pr'],
            'empat_belas_tahun_lk' => $row['empat_belas_tahun_lk'],
            'empat_belas_tahun_pr' => $row['empat_belas_tahun_pr'],
            'lima_belas_tahun_lk' => $row['lima_belas_tahun_lk'],
            'lima_belas_tahun_pr' => $row['lima_belas_tahun_pr'],
            'enam_belas_tahun_lk' => $row['enam_belas_tahun_lk'],
            'enam_belas_tahun_pr' => $row['enam_belas_tahun_pr'],
            'tujuh_belas_tahun_lk' => $row['tujuh_belas_tahun_lk'],
            'tujuh_belas_tahun_pr' => $row['tujuh_belas_tahun_pr'],
            'delapan_belas_tahun_lk' => $row['delapan_belas_tahun_lk'],
            'delapan_belas_tahun_pr' => $row['delapan_belas_tahun_pr'],
            'sembilan_belas_tahun_lk' => $row['sembilan_belas_tahun_lk'],
            'sembilan_belas_tahun_pr' => $row['sembilan_belas_tahun_pr'],
            'dua_puluh_tahun_lk' => $row['dua_puluh_tahun_lk'],
            'dua_puluh_tahun_pr' => $row['dua_puluh_tahun_pr'],

            'dua_puluh_satu_tahun_lk' => $row['dua_puluh_satu_tahun_lk'],
            'dua_puluh_satu_tahun_pr' => $row['dua_puluh_satu_tahun_pr'],
            'dua_puluh_dua_tahun_lk' => $row['dua_puluh_dua_tahun_lk'],
            'dua_puluh_dua_tahun_pr' => $row['dua_puluh_dua_tahun_pr'],
            'dua_puluh_tiga_tahun_lk' => $row['dua_puluh_tiga_tahun_lk'],
            'dua_puluh_tiga_tahun_pr' => $row['dua_puluh_tiga_tahun_pr'],
            'dua_puluh_empat_tahun_lk' => $row['dua_puluh_empat_tahun_lk'],
            'dua_puluh_empat_tahun_pr' => $row['dua_puluh_empat_tahun_pr'],
            'dua_puluh_lima_tahun_lk' => $row['dua_puluh_lima_tahun_lk'],
            'dua_puluh_lima_tahun_pr' => $row['dua_puluh_lima_tahun_pr'],
            'dua_puluh_enam_tahun_lk' => $row['dua_puluh_enam_tahun_lk'],
            'dua_puluh_enam_tahun_pr' => $row['dua_puluh_enam_tahun_pr'],
            'dua_puluh_tujuh_tahun_lk' => $row['dua_puluh_tujuh_tahun_lk'],
            'dua_puluh_tujuh_tahun_pr' => $row['dua_puluh_tujuh_tahun_pr'],
            'dua_puluh_delapan_tahun_lk' => $row['dua_puluh_delapan_tahun_lk'],
            'dua_puluh_delapan_tahun_pr' => $row['dua_puluh_delapan_tahun_pr'],
            'dua_puluh_sembilan_tahun_lk' => $row['dua_puluh_sembilan_tahun_lk'],
            'dua_puluh_sembilan_tahun_pr' => $row['dua_puluh_sembilan_tahun_pr'],
            'tiga_puluh_tahun_lk' => $row['tiga_puluh_tahun_lk'],
            'tiga_puluh_tahun_pr' => $row['tiga_puluh_tahun_pr'],

            'tiga_puluh_satu_tahun_lk' => $row['tiga_puluh_satu_tahun_lk'],
            'tiga_puluh_satu_tahun_pr' => $row['tiga_puluh_satu_tahun_pr'],
            'tiga_puluh_dua_tahun_lk' => $row['tiga_puluh_dua_tahun_lk'],
            'tiga_puluh_dua_tahun_pr' => $row['tiga_puluh_dua_tahun_pr'],
            'tiga_puluh_tiga_tahun_lk' => $row['tiga_puluh_tiga_tahun_lk'],
            'tiga_puluh_tiga_tahun_pr' => $row['tiga_puluh_tiga_tahun_pr'],
            'tiga_puluh_empat_tahun_lk' => $row['tiga_puluh_empat_tahun_lk'],
            'tiga_puluh_empat_tahun_pr' => $row['tiga_puluh_empat_tahun_pr'],
            'tiga_puluh_lima_tahun_lk' => $row['tiga_puluh_lima_tahun_lk'],
            'tiga_puluh_lima_tahun_pr' => $row['tiga_puluh_lima_tahun_pr'],
            'tiga_puluh_enam_tahun_lk' => $row['tiga_puluh_enam_tahun_lk'],
            'tiga_puluh_enam_tahun_pr' => $row['tiga_puluh_enam_tahun_pr'],
            'tiga_puluh_tujuh_tahun_lk' => $row['tiga_puluh_tujuh_tahun_lk'],
            'tiga_puluh_tujuh_tahun_pr' => $row['tiga_puluh_tujuh_tahun_pr'],
            'tiga_puluh_delapan_tahun_lk' => $row['tiga_puluh_delapan_tahun_lk'],
            'tiga_puluh_delapan_tahun_pr' => $row['tiga_puluh_delapan_tahun_pr'],
            'tiga_puluh_sembilan_tahun_lk' => $row['tiga_puluh_sembilan_tahun_lk'],
            'tiga_puluh_sembilan_tahun_pr' => $row['tiga_puluh_sembilan_tahun_pr'],
            'empat_puluh_tahun_lk' => $row['empat_puluh_tahun_lk'],
            'empat_puluh_tahun_pr' => $row['empat_puluh_tahun_pr'],

            'empat_puluh_satu_tahun_lk' => $row['empat_puluh_satu_tahun_lk'],
            'empat_puluh_satu_tahun_pr' => $row['empat_puluh_satu_tahun_pr'],
            'empat_puluh_dua_tahun_lk' => $row['empat_puluh_dua_tahun_lk'],
            'empat_puluh_dua_tahun_pr' => $row['empat_puluh_dua_tahun_pr'],
            'empat_puluh_tiga_tahun_lk' => $row['empat_puluh_tiga_tahun_lk'],
            'empat_puluh_tiga_tahun_pr' => $row['empat_puluh_tiga_tahun_pr'],
            'empat_puluh_empat_tahun_lk' => $row['empat_puluh_empat_tahun_lk'],
            'empat_puluh_empat_tahun_pr' => $row['empat_puluh_empat_tahun_pr'],
            'empat_puluh_lima_tahun_lk' => $row['empat_puluh_lima_tahun_lk'],
            'empat_puluh_lima_tahun_pr' => $row['empat_puluh_lima_tahun_pr'],
            'empat_puluh_enam_tahun_lk' => $row['empat_puluh_enam_tahun_lk'],
            'empat_puluh_enam_tahun_pr' => $row['empat_puluh_enam_tahun_pr'],
            'empat_puluh_tujuh_tahun_lk' => $row['empat_puluh_tujuh_tahun_lk'],
            'empat_puluh_tujuh_tahun_pr' => $row['empat_puluh_tujuh_tahun_pr'],
            'empat_puluh_delapan_tahun_lk' => $row['empat_puluh_delapan_tahun_lk'],
            'empat_puluh_delapan_tahun_pr' => $row['empat_puluh_delapan_tahun_pr'],
            'empat_puluh_sembilan_tahun_lk' => $row['empat_puluh_sembilan_tahun_lk'],
            'empat_puluh_sembilan_tahun_pr' => $row['empat_puluh_sembilan_tahun_pr'],
            'lima_puluh_tahun_lk' => $row['lima_puluh_tahun_lk'],
            'lima_puluh_tahun_pr' => $row['lima_puluh_tahun_pr'],

            'lima_puluh_satu_tahun_lk' => $row['lima_puluh_satu_tahun_lk'],
            'lima_puluh_satu_tahun_pr' => $row['lima_puluh_satu_tahun_pr'],
            'lima_puluh_dua_tahun_lk' => $row['lima_puluh_dua_tahun_lk'],
            'lima_puluh_dua_tahun_pr' => $row['lima_puluh_dua_tahun_pr'],
            'lima_puluh_tiga_tahun_lk' => $row['lima_puluh_tiga_tahun_lk'],
            'lima_puluh_tiga_tahun_pr' => $row['lima_puluh_tiga_tahun_pr'],
            'lima_puluh_empat_tahun_lk' => $row['lima_puluh_empat_tahun_lk'],
            'lima_puluh_empat_tahun_pr' => $row['lima_puluh_empat_tahun_pr'],
            'lima_puluh_lima_tahun_lk' => $row['lima_puluh_lima_tahun_lk'],
            'lima_puluh_lima_tahun_pr' => $row['lima_puluh_lima_tahun_pr'],
            'lima_puluh_enam_tahun_lk' => $row['lima_puluh_enam_tahun_lk'],
            'lima_puluh_enam_tahun_pr' => $row['lima_puluh_enam_tahun_pr'],
            'lima_puluh_tujuh_tahun_lk' => $row['lima_puluh_tujuh_tahun_lk'],
            'lima_puluh_tujuh_tahun_pr' => $row['lima_puluh_tujuh_tahun_pr'],
            'lima_puluh_delapan_tahun_lk' => $row['lima_puluh_delapan_tahun_lk'],
            'lima_puluh_delapan_tahun_pr' => $row['lima_puluh_delapan_tahun_pr'],
            'lima_puluh_sembilan_tahun_lk' => $row['lima_puluh_sembilan_tahun_lk'],
            'lima_puluh_sembilan_tahun_pr' => $row['lima_puluh_sembilan_tahun_pr'],
            'lima_puluh_sembilan_tahun_lk' => $row['lima_puluh_sembilan_tahun_lk'],
            'lima_puluh_sembilan_tahun_pr' => $row['lima_puluh_sembilan_tahun_pr'],
            'enam_puluh_tahun_lk' => $row['enam_puluh_tahun_lk'],
            'enam_puluh_tahun_pr' => $row['enam_puluh_tahun_pr'],

            'enam_puluh_satu_tahun_lk' => $row['enam_puluh_satu_tahun_lk'],
            'enam_puluh_satu_tahun_pr' => $row['enam_puluh_satu_tahun_pr'],
            'enam_puluh_dua_tahun_lk' => $row['enam_puluh_dua_tahun_lk'],
            'enam_puluh_dua_tahun_pr' => $row['enam_puluh_dua_tahun_pr'],
            'enam_puluh_tiga_tahun_lk' => $row['enam_puluh_tiga_tahun_lk'],
            'enam_puluh_tiga_tahun_pr' => $row['enam_puluh_tiga_tahun_pr'],
            'enam_puluh_empat_tahun_lk' => $row['enam_puluh_empat_tahun_lk'],
            'enam_puluh_empat_tahun_pr' => $row['enam_puluh_empat_tahun_pr'],
            'enam_puluh_lima_tahun_lk' => $row['enam_puluh_lima_tahun_lk'],
            'enam_puluh_lima_tahun_pr' => $row['enam_puluh_lima_tahun_pr'],
            'enam_puluh_enam_tahun_lk' => $row['enam_puluh_enam_tahun_lk'],
            'enam_puluh_enam_tahun_pr' => $row['enam_puluh_enam_tahun_pr'],
            'enam_puluh_tujuh_tahun_lk' => $row['enam_puluh_tujuh_tahun_lk'],
            'enam_puluh_tujuh_tahun_pr' => $row['enam_puluh_tujuh_tahun_pr'],
            'enam_puluh_delapan_tahun_lk' => $row['enam_puluh_delapan_tahun_lk'],
            'enam_puluh_delapan_tahun_pr' => $row['enam_puluh_delapan_tahun_pr'],
            'enam_puluh_sembilan_tahun_lk' => $row['enam_puluh_sembilan_tahun_lk'],
            'enam_puluh_sembilan_tahun_pr' => $row['enam_puluh_sembilan_tahun_pr'],
            'tujuh_puluh_tahun_lk' => $row['tujuh_puluh_tahun_lk'],
            'tujuh_puluh_tahun_pr' => $row['tujuh_puluh_tahun_pr'],

            'tujuh_puluh_satu_tahun_lk' => $row['tujuh_puluh_satu_tahun_lk'],
            'tujuh_puluh_satu_tahun_pr' => $row['tujuh_puluh_satu_tahun_pr'],
            'tujuh_puluh_dua_tahun_lk' => $row['tujuh_puluh_dua_tahun_lk'],
            'tujuh_puluh_dua_tahun_pr' => $row['tujuh_puluh_dua_tahun_pr'],
            'tujuh_puluh_tiga_tahun_lk' => $row['tujuh_puluh_tiga_tahun_lk'],
            'tujuh_puluh_tiga_tahun_pr' => $row['tujuh_puluh_tiga_tahun_pr'],
            'tujuh_puluh_empat_tahun_lk' => $row['tujuh_puluh_empat_tahun_lk'],
            'tujuh_puluh_empat_tahun_pr' => $row['tujuh_puluh_empat_tahun_pr'],
            'tujuh_puluh_lima_tahun_lk' => $row['tujuh_puluh_lima_tahun_lk'],
            'tujuh_puluh_lima_tahun_pr' => $row['tujuh_puluh_lima_tahun_pr'],
            'tujuh_puluh_enam_tahun_lk' => $row['tujuh_puluh_enam_tahun_lk'],
            'tujuh_puluh_enam_tahun_pr' => $row['tujuh_puluh_enam_tahun_pr'],
            'tujuh_puluh_tujuh_tahun_lk' => $row['tujuh_puluh_tujuh_tahun_lk'],
            'tujuh_puluh_tujuh_tahun_pr' => $row['tujuh_puluh_tujuh_tahun_pr'],
            'tujuh_puluh_delapan_tahun_lk' => $row['tujuh_puluh_delapan_tahun_lk'],
            'tujuh_puluh_delapan_tahun_pr' => $row['tujuh_puluh_delapan_tahun_pr'],
            'tujuh_puluh_sembilan_tahun_lk' => $row['tujuh_puluh_sembilan_tahun_lk'],
            'tujuh_puluh_sembilan_tahun_pr' => $row['tujuh_puluh_sembilan_tahun_pr'],
            'delapan_puluh_tahun_lk' => $row['delapan_puluh_tahun_lk'],
            'delapan_puluh_tahun_pr' => $row['delapan_puluh_tahun_pr'],

            'delapan_puluh_satu_tahun_lk' => $row['delapan_puluh_satu_tahun_lk'],
            'delapan_puluh_satu_tahun_pr' => $row['delapan_puluh_satu_tahun_pr'],
            'delapan_puluh_dua_tahun_lk' => $row['delapan_puluh_dua_tahun_lk'],
            'delapan_puluh_dua_tahun_pr' => $row['delapan_puluh_dua_tahun_pr'],
            'delapan_puluh_tiga_tahun_lk' => $row['delapan_puluh_tiga_tahun_lk'],
            'delapan_puluh_tiga_tahun_pr' => $row['delapan_puluh_tiga_tahun_pr'],
            'delapan_puluh_empat_tahun_lk' => $row['delapan_puluh_empat_tahun_lk'],
            'delapan_puluh_empat_tahun_pr' => $row['delapan_puluh_empat_tahun_pr'],
            'delapan_puluh_lima_tahun_lk' => $row['delapan_puluh_lima_tahun_lk'],
            'delapan_puluh_lima_tahun_pr' => $row['delapan_puluh_lima_tahun_pr'],
            'delapan_puluh_enam_tahun_lk' => $row['delapan_puluh_enam_tahun_lk'],
            'delapan_puluh_enam_tahun_pr' => $row['delapan_puluh_enam_tahun_pr'],
            'delapan_puluh_tujuh_tahun_lk' => $row['delapan_puluh_tujuh_tahun_lk'],
            'delapan_puluh_tujuh_tahun_pr' => $row['delapan_puluh_tujuh_tahun_pr'],
            'delapan_puluh_delapan_tahun_lk' => $row['delapan_puluh_delapan_tahun_lk'],
            'delapan_puluh_delapan_tahun_pr' => $row['delapan_puluh_delapan_tahun_pr'],
            'delapan_puluh_sembilan_tahun_lk' => $row['delapan_puluh_sembilan_tahun_lk'],
            'delapan_puluh_sembilan_tahun_pr' => $row['delapan_puluh_sembilan_tahun_pr'],
            'sembilan_puluh_tahun_lk' => $row['sembilan_puluh_tahun_lk'],
            'sembilan_puluh_tahun_pr' => $row['sembilan_puluh_tahun_pr'],

            'sembilan_puluh_satu_tahun_lk' => $row['sembilan_puluh_satu_tahun_lk'],
            'sembilan_puluh_satu_tahun_pr' => $row['sembilan_puluh_satu_tahun_pr'],
            'sembilan_puluh_dua_tahun_lk' => $row['sembilan_puluh_dua_tahun_lk'],
            'sembilan_puluh_dua_tahun_pr' => $row['sembilan_puluh_dua_tahun_pr'],
            'sembilan_puluh_tiga_tahun_lk' => $row['sembilan_puluh_tiga_tahun_lk'],
            'sembilan_puluh_tiga_tahun_pr' => $row['sembilan_puluh_tiga_tahun_pr'],
            'sembilan_puluh_empat_tahun_lk' => $row['sembilan_puluh_empat_tahun_lk'],
            'sembilan_puluh_empat_tahun_pr' => $row['sembilan_puluh_empat_tahun_pr'],
            'sembilan_puluh_lima_tahun_lk' => $row['sembilan_puluh_lima_tahun_lk'],
            'sembilan_puluh_lima_tahun_pr' => $row['sembilan_puluh_lima_tahun_pr'],
            'sembilan_puluh_enam_tahun_lk' => $row['sembilan_puluh_enam_tahun_lk'],
            'sembilan_puluh_enam_tahun_pr' => $row['sembilan_puluh_enam_tahun_pr'],
            'sembilan_puluh_tujuh_tahun_lk' => $row['sembilan_puluh_tujuh_tahun_lk'],
            'sembilan_puluh_tujuh_tahun_pr' => $row['sembilan_puluh_tujuh_tahun_pr'],
            'sembilan_puluh_delapan_tahun_lk' => $row['sembilan_puluh_delapan_tahun_lk'],
            'sembilan_puluh_delapan_tahun_pr' => $row['sembilan_puluh_delapan_tahun_pr'],
            'sembilan_puluh_sembilan_tahun_lk' => $row['sembilan_puluh_sembilan_tahun_lk'],
            'sembilan_puluh_sembilan_tahun_pr' => $row['sembilan_puluh_sembilan_tahun_pr'],
            'seratus_tahun_lk' => $row['seratus_tahun_lk'],
            'seratus_tahun_pr' => $row['seratus_tahun_pr'],

            'seratus_satu_tahun_lk' => $row['seratus_satu_tahun_lk'],
            'seratus_satu_tahun_pr' => $row['seratus_satu_tahun_pr'],
            'seratus_dua_tahun_lk' => $row['seratus_dua_tahun_lk'],
            'seratus_dua_tahun_pr' => $row['seratus_dua_tahun_pr'],
            'seratus_tiga_tahun_lk' => $row['seratus_tiga_tahun_lk'],
            'seratus_tiga_tahun_pr' => $row['seratus_tiga_tahun_pr'],
            'seratus_empat_tahun_lk' => $row['seratus_empat_tahun_lk'],
            'seratus_empat_tahun_pr' => $row['seratus_empat_tahun_pr'],
            'seratus_lima_tahun_lk' => $row['seratus_lima_tahun_lk'],
            'seratus_lima_tahun_pr' => $row['seratus_lima_tahun_pr'],
            'seratus_enam_tahun_lk' => $row['seratus_enam_tahun_lk'],
            'seratus_enam_tahun_pr' => $row['seratus_enam_tahun_pr'],
            'seratus_tujuh_tahun_lk' => $row['seratus_tujuh_tahun_lk'],
            'seratus_tujuh_tahun_pr' => $row['seratus_tujuh_tahun_pr'],
            'seratus_delapan_tahun_lk' => $row['seratus_delapan_tahun_lk'],
            'seratus_delapan_tahun_pr' => $row['seratus_delapan_tahun_pr'],
            'seratus_sembilan_tahun_lk' => $row['seratus_sembilan_tahun_lk'],
            'seratus_sembilan_tahun_pr' => $row['seratus_sembilan_tahun_pr'],
            'seratus_sepuluh_tahun_lk' => $row['seratus_sepuluh_tahun_lk'],
            'seratus_sepuluh_tahun_pr' => $row['seratus_sepuluh_tahun_pr'],
            'seratus_sebelas_tahun_lk' => $row['seratus_sebelas_tahun_lk'],
            'seratus_sebelas_tahun_pr' => $row['seratus_sebelas_tahun_pr'],
            'seratus_dua_belas_tahun_lk' => $row['seratus_dua_belas_tahun_lk'],
            'seratus_dua_belas_tahun_pr' => $row['seratus_dua_belas_tahun_pr'],
            'seratus_tiga_belas_tahun_lk' => $row['seratus_tiga_belas_tahun_lk'],
            'seratus_tiga_belas_tahun_pr' => $row['seratus_tiga_belas_tahun_pr'],
            'seratus_empat_belas_tahun_lk' => $row['seratus_empat_belas_tahun_lk'],
            'seratus_empat_belas_tahun_pr' => $row['seratus_empat_belas_tahun_pr'],
            'seratus_lima_belas_tahun_lk' => $row['seratus_lima_belas_tahun_lk'],
            'seratus_lima_belas_tahun_pr' => $row['seratus_lima_belas_tahun_pr'],
            'seratus_enam_belas_tahun_lk' => $row['seratus_enam_belas_tahun_lk'],
            'seratus_enam_belas_tahun_pr' => $row['seratus_enam_belas_tahun_pr'],
            'seratus_tujuh_belas_tahun_lk' => $row['seratus_tujuh_belas_tahun_lk'],
            'seratus_tujuh_belas_tahun_pr' => $row['seratus_tujuh_belas_tahun_pr'],
            'seratus_delapan_belas_tahun_lk' => $row['seratus_delapan_belas_tahun_lk'],
            'seratus_delapan_belas_tahun_pr' => $row['seratus_delapan_belas_tahun_pr'],
            'seratus_sembilan_belas_tahun_lk' => $row['seratus_sembilan_belas_tahun_lk'],
            'seratus_sembilan_belas_tahun_pr' => $row['seratus_sembilan_belas_tahun_pr'],
            'seratus_dua_puluh_tahun_lk' => $row['seratus_dua_puluh_tahun_lk'],
            'seratus_dua_puluh_tahun_pr' => $row['seratus_dua_puluh_tahun_pr'],

            'seratus_dua_puluh_satu_tahun_lk' => $row['seratus_dua_puluh_satu_tahun_lk'],
            'seratus_dua_puluh_satu_tahun_pr' => $row['seratus_dua_puluh_satu_tahun_pr'],
          
        ]);
    }
}